### PR TITLE
Bump version to 1.4.6 for Swift 5

### PR DESCRIPTION
**Pull request by pvzig**

### CODE REVIEW

**Comment by Vkt0r** [comment]
@pvzig Thanks for creating this PR. I was planning to make a PR with this tomorrow 😅. It was happening a weird crash with the `tvOS` tests. I re-run it again and now it's green!

**Comment by Vkt0r** [comment]
@pvzig There is only one small piece of code we're missing to update and I think we have missed it for a while.

https://github.com/httpswift/swifter/blob/2c274ed4f653b2e8f26195a116eedb17129052a4/Sources/HttpServer.swift#L12

We need to update this variable from the resources, but we can create a PR for that at some point later.

**Comment by pvzig** [comment]
Did the lazy thing for now and bumped it manually 🙃

**Review by Vkt0r — APPROVED** [review]
Looks good!

**Comment by pvzig** [comment]
Tagged a [release](https://github.com/httpswift/swifter/releases/tag/1.4.6) and pushed it to [CocoaPods Trunk](https://github.com/CocoaPods/Specs/blob/master/Specs/4/2/2/Swifter/1.4.6/Swifter.podspec.json).

**Comment by Vkt0r** [comment]
Cool @pvzig thanks!

**Pull request merged**
