### PR TITLE
Change HttpResponseBody.json to take Any

### PR DESCRIPTION
**Pull request by edwinveger**
This PR addresses issue #392 . I have added several unit tests for this behavior.

### CODE REVIEW

**Comment by edwinveger** [comment]
I only noticed just now that there is a similar PR (#390). However, that PR does not add any tests for the new behavior.

**Comment by Mazyod** [comment]
Thanks for adding the tests.

**Comment by Vkt0r** [comment]
Hey, @edwinveger Thanks for taking the time to create this! Can you please update the `CHANGELOG.md` and I would be happy to merge the PR

**Comment by edwinveger** [comment]
@Vkt0r took me a while, but done.

**Comment by Vkt0r** [comment]
Hey, @edwinveger thanks! Can you please rebase and clean the branch?

**Comment by edwinveger** [comment]
@Vkt0r rebase done. By cleaning the branch, do you mean squashing the commits?

Tests are failing to compile on Linux, but I'm not sure how I can fix that.

This is my first open-source PR, thanks for your patience 😁

**Comment by Vkt0r** [comment]
Hey, @edwinveger No problem at all 😉. Don't worry about the Linux tests, I've to report this issue to CircleCI with the Docker image. I'll check out your branch in the meantime and I'll run it locally in my machine with Docker in Linux. Can you please squash your commits ? If everything is running for me locally I'll merge it !

**Comment by Vkt0r** [comment]
@edwinveger I checked your PR locally and it's failing with some tests and also I rerun the failed jobs in CircleCI as they have issues as I mentioned before and now the failed jobs reflect the failed tests see details in the PR, please.

**Comment by Vkt0r** [comment]
Hey, @edwinveger I was checking out your PR and I figured out what was wrong with it in Linux! We have some compilation conditions for platforms in that specific part of the code and it's not necessary anymore:

https://github.com/httpswift/swifter/blob/2f60ae4676814706ae02fee225315336a550282c/XCode/Sources/HttpResponse.swift#L34-L53

The condition is not longer necessary as we can use `JSONSerialization` in Linux now. So replacing it with:

```swift
case .json(let object):
    guard JSONSerialization.isValidJSONObject(object) else {
        throw SerializationError.invalidObject
    }
    let data = try JSONSerialization.data(withJSONObject: object)
    return (data.count, {
        try $0.write(data)
    })
```

Would make your tests pass on macOS and Linux 😄. Can you please update your PR to reflect this change ?

**Comment by edwinveger** [comment]
Thanks for the research. I’m on holiday now, I’ll pick this up when I’m back (end of May).

**Review by Vkt0r — APPROVED** [review]
This looks good! Thanks for your contribution @edwinveger.

**Pull request merged**
