### PR TITLE
Don’t embed standard Swift libs for tvOS target.

### PR DESCRIPTION
**Pull request by matthewryan**
- unchecked `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` on tvOS target in line with other platform targets
- apps with Swifter embedded would not pass App Store checks due to `Frameworks` directory

### CODE REVIEW

**Comment by Vkt0r** [comment]
Hey, @matthewryan Thanks for taking the time to create this PR 😀. As you said the rest of the platforms are complaint with not embed the Swift standard libraries and this has been an issue with the App Store with other libraries. 

Can you clean up your PR rebasing from `stable` to keep only the change you're mentioning?

**Comment by Vkt0r** [comment]
@matthewryan As soon as you clean it we can merge it. Are you able to clean it up or do you need any help?

**Comment by Vkt0r** [comment]
Hey, @matthewryan 👋 are you interested in continuing with this PR? Can you please see my above comments to be able it to merge it ?

**Comment by adamkaplan** [comment]
@matthewryan Ping! Not much effort remaining to get merged... it's just a bit out of date now.

**Comment by Vkt0r** [comment]
@adamkaplan I'll take care of this directly in the current branch as I think it could be helpful for more people if @matthewryan is not available.

**Comment by Vkt0r** [comment]
Closing this in favor of #361.

**Pull request closed without merging**
