### PR TITLE
Import FoundationNetworking on Linux to fix tests.

### PR DESCRIPTION
**Pull request by kbongort**
FoundationNetworking is required for NSURLSession and such.

### CODE REVIEW

**Comment by Vkt0r** [comment]
Hey, @kbongort Thanks for taking the time to fix this! I already integrated your changes in a draft PR #448 I've to fix the Linux infrastructure issue with CircleCI. Please rebase and update this PR in order to merge it.

**Comment by kbongort** [comment]
@Vkt0r do you need me to update this PR or should I just close it since you've incorporated the same changes into #448?

**Comment by Vkt0r** [comment]
@kbongort Please update it to merge it. I integrated your changes to test my branch, I'll rebase it once yours is in the `stable` branch.

**Comment by kbongort** [comment]
@Vkt0r Ok, I've updated this PR.

**Pull request merged**
