### PR TITLE
Adds response body to any http response

### PR DESCRIPTION
**Pull request by mtgto**
I want to set response body to any response besides 200 ok.

### CODE REVIEW

**Comment by Vkt0r** [comment]
@mtgto Please can you rebase this PR to continue reviewing it ? Thanks

**Comment by mtgto** [comment]
@Vkt0r merge stable. It seems this PR is not related CI fails.

**Comment by michaelenger** [comment]
I am unable to replicate the CI test failures locally, so I'm going to merge this in.

**Comment by mtgto** [comment]
😍

**Pull request merged**
