### PR TITLE
Disambiguate swift method call

### PR DESCRIPTION
**Pull request by adamkaplan**

### CODE REVIEW

**Comment by adamkaplan** [comment]
Test pass locally for iOS on Swift 4.0 and 4.2. Not sure how this didn't show up earlier – possibly due to my use of Xcode 10 beta vs release.

screenshot 2019-02-18 15 51 45

**Comment by adamkaplan** [comment]
After more research, not only does this issue only occur in the latest Beta Xcode 10.2 (10P82s), but the fix actually breaks non-beta Xcode 10.1 (10B61)!

Not sure what to do here, but it should not be merged just yet...

**Comment by stevenp** [comment]
It would be helpful if you could open an issue for this so that anyone searching for it can more easily find it. I spent quite a bit of time coming to the same fix and only stumbled upon your branch by accident.

**Comment by alanzeino** [comment]
> After more research, not only does this issue only occur in the latest Beta Xcode 10.2 (10P82s), but the fix actually breaks non-beta Xcode 10.1 (10B61)!
> 
> Not sure what to do here, but it should not be merged just yet...

I've been working on updating this library to 4.2 + Xcode 10.2, and 5.0 + Xcode 10.2. The answer is to conditionally compile the new code:

```
#if swift(>=4.2.2)
        return String(cString: UnsafePointer<UInt8>(strerror(errno)))
#else
        return String(cString: UnsafePointer(strerror(errno)))
#endif
```

This works because the new version of Swift 4.2 in Xcode 10.2 is 4.2.2.

**Comment by Vkt0r** [comment]
@alanzeino That's a good catch 👍. 

>I've been working on updating this library to 4.2 + Xcode 10.2, and 5.0 + Xcode 10.2.

I can assume we can expect a  draft PR soon then with the update 😅 ?

**Comment by platonsi** [comment]
Hello,

I actually opened an issue for this because I didn't find this PR (thanks @Vkt0r for referencing). In order to fix this you can simply remove the 
UnsafePointer. You can see the discussion at the [Apple Forum](https://forums.developer.apple.com/thread/113919)

**Comment by alanzeino** [comment]
> @alanzeino That's a good catch 👍.
> 
> > I've been working on updating this library to 4.2 + Xcode 10.2, and 5.0 + Xcode 10.2.
> 
> I can assume we can expect a draft PR soon then with the update 😅 ?

I'm close, just got one issue to solve and I can PR it.

**Comment by alanzeino** [comment]
In Xcode 10.2b4 this change isn't needed anymore.

**Comment by Vkt0r** [comment]
Closing this in favor of #370.

**Pull request closed without merging**
