### PR TITLE
Change version to 1.4.3

### PR DESCRIPTION
**Pull request by ignatovSA**
1.4.3 because 1.4.2 is not suitable, as there is a tag but version isn't updated in the podspec.

Also, please create a `1.4.3` tag.

### CODE REVIEW

**Comment by amardeepranu** [comment]
Can you merge this? I'm unable to continue work with the Xcode 10 error.

**Comment by ignatovSA** [comment]
@julien-c Could you please merge this PR? This will significantly ease the pod usage with Xcode 10.

**Comment by muskacirca** [comment]
I see you have the situation in hand :) We're all waiting for this update !

**Comment by StarLard** [comment]
Will this be merged soon? Need an update on this issue.

**Comment by limerickgds** [comment]
@julien-c plz create 1.4.3.

**Comment by menasameh** [comment]
Any updates on this ?

**Comment by julien-c** [comment]
done

**Comment by ignatovSA** [comment]
Very thanks, @julien-c!

Please do not forget to create `1.4.3` Tag, so CocoaPods will be up-to-date

**Pull request merged**
