### PR TITLE
Added support for using ** as a catch-all at the end of a route

### PR DESCRIPTION
**Pull request by michaelenger**
This allows you to use `**` as a catch-all at the end of a route without breaking its support in the middle of a route. For example, the route `/test/**` would match all of the following:

```
/test/one
/test/one/two
/test/one/two/three/four/five/six
```

This is a potential solution to the scenarios discussed in #405 but won't necessarily work if you're using a variable in the route. I instead use `request.path` in my handler function to perform any logic based on the matched path.

### CODE REVIEW

**Comment by diginick** [comment]
Any updates on the merging of this PR?

**Comment by Vkt0r** [comment]
Hey @michaelenger, thanks for contribution! I'll be reviewing this PR in the next days, sorry for the delay 😞.

**Comment by Vkt0r** [comment]
@michaelenger Can you please rebase your PR in order to be able to finish the review ? Thanks and sorry for the delay again.

**Comment by michaelenger** [comment]
@Vkt0r I've merged in the changes from the `stable` branch.

**Comment by SamCosta1** [comment]
Can this be merged? This change would enable me to fully transition from GCDWebServer

**Comment by Vkt0r** [comment]
Sorry for the delay guys and thanks @michaelenger for your contribution!

**Comment by ritxweb** [comment]
Hi

I've trying to use the wildcard route to match all the routes and handle them after by the request param. I have tried with server["\*\*"] and server["/\*\*"] but there is no way to catch any request, even index.html using http://localhost/. Am I doing something wrong?

As workaround I am using the call of notFoundHandler but I don't know if this is the right  way to achieve it.

Please, any help would be much appreciated.

Regards.

**Pull request merged**
